[build]
  command = "npm run build"
  publish = "dist"
  ignore_warnings = true

[build.environment]
  NODE_VERSION = "14"

[context.production.environment]
  VUE_APP_ENV = "production"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true